

export const commands = [
  "Sing a song",
  "Run",
  "Jump",
  "Dance",
  "Tell a joke",
  "Do 10 push-ups",
  "Kiss one of us 😆",
  "Act like a monkey",
  "Say the alphabet backwards",
  "Do your best superhero pose 🦸‍♂️",
  "Jump on one foot for 20 seconds",
  "Talk in a funny accent for 1 minute",
  "Balance a book on your head for 10 seconds",
  "Pretend to be a chicken 🐔",
  "Do a dramatic movie scene 🎬",
  "Imitate your favorite celebrity",
  "Try to lick your elbow 😜",
  "Speak only in rhymes for 30 seconds",
  "Make a funny face and hold it",
  "Jump as high as you can 5 times",
  "Pretend to be a zombie 🧟",
  "Do 5 jumping jacks while singing",
  "March like a soldier across the room",
  "Hop on one foot for 20 seconds",
  "Pretend to swim on land",
  "Say 'BEBEG BET BEG BEGA' fast",
  "Crawl like a baby for 5 meters",
  "Spin around 5 times and walk straight",
  "Make animal noises ",
  "Run to a wall and back",
  "Pretend to be a news reporter",
  "Make up a new dance move",
  "Speak in a whisper until your next turn",
  "Draw a mustache on your face with your finger",
  "እስከሚቀጥለው ተራህ ድረስ ሃውልት እንደሆንክ አስመስለህ",
  "Sing everything you say for 1 minute",
  "Walk like a crab for 20 seconds",
  " እንደ ጥንቸል ይዝለሉ",
  "Pretend to ride a horse",
  "Do 10 sit-ups while counting loudly",
  "Act like a cat and purr loudly",
  "Dance like no one is watching",
  "Invent a new word and use it in a sentence",
  "Pretend to be a robot making coffee",
  "Make a funny animal hybrid sound",
  "Do a slow-motion run across the room",
];
